system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
    constraints: {}
frontend.enableClientVersionCheck:
  - value: false
    constraints: {}
limit.maxIDLength:
  - value: 255
    constraints: {}
