apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payment-switch
resources:
  - ../staging/kustomization.yaml
  - mock-vault.yaml
  - external-secrets-local.yaml
  - ../staging/temporal-apisix.yaml
patches:
  - path: app-config-patch.yaml
